#include "parser/parser.hpp"
#include <stdexcept>
#include <cstdlib>
namespace nexus {
const Token& Parser::cur()const{return tokens_.at(i_);} bool Parser::accept(TokenKind k){if(cur().kind==k){++i_;return true;}return false;} Token Parser::expect(TokenKind k){if(cur().kind!=k)throw std::runtime_error(std::string("expected ")+tokenName(k)+", got "+tokenName(cur().kind));return tokens_[i_++];}
Type Parser::parseType(){auto t=expect(TokenKind::Identifier); if(t.text=="i64"||t.text=="int")return Type::i64(); if(t.text=="bool")return Type::boolean(); if(t.text=="string")return Type::string(); if(t.text=="void")return Type::void_(); throw std::runtime_error("unknown type: "+t.text);}
Program Parser::parseProgram(){Program p;while(cur().kind!=TokenKind::End)p.functions.push_back(parseFunction());return p;}
Function Parser::parseFunction(){expect(TokenKind::KwFn);auto name=expect(TokenKind::Identifier);expect(TokenKind::LParen);std::vector<Param> ps;if(cur().kind!=TokenKind::RParen){for(;;){auto n=expect(TokenKind::Identifier);expect(TokenKind::Colon);ps.push_back({n.text,parseType()});if(!accept(TokenKind::Comma))break;}}expect(TokenKind::RParen);Type ret=Type::void_();if(accept(TokenKind::Arrow))ret=parseType();auto body=parseBlock();return {name.text,std::move(ps),ret,std::move(body)};}
std::unique_ptr<Block> Parser::parseBlock(){expect(TokenKind::LBrace);auto b=std::make_unique<Block>();while(cur().kind!=TokenKind::RBrace&&cur().kind!=TokenKind::End)b->statements.push_back(parseStmt());expect(TokenKind::RBrace);return b;}
Stmt::Ptr Parser::parseStmt(){if(accept(TokenKind::KwLet)){bool mut=accept(TokenKind::KwMut);auto n=expect(TokenKind::Identifier);Type ty; if(accept(TokenKind::Colon))ty=parseType();expect(TokenKind::Equal);auto e=parseExpr();accept(TokenKind::Semicolon);auto s=std::make_unique<LetStmt>();s->name=n.text;s->mut=mut;s->type=ty;s->init=std::move(e);return s;} if(accept(TokenKind::KwReturn)){auto e=cur().kind==TokenKind::RBrace?nullptr:parseExpr();accept(TokenKind::Semicolon);auto s=std::make_unique<ReturnStmt>();s->expr=std::move(e);return s;} if(accept(TokenKind::KwIf)){auto c=parseExpr();auto t=parseBlock();std::unique_ptr<Block> e;if(accept(TokenKind::KwElse))e=parseBlock();auto s=std::make_unique<IfStmt>();s->cond=std::move(c);s->thenBlock=std::move(t);s->elseBlock=std::move(e);return s;} if(accept(TokenKind::KwWhile)){auto c=parseExpr();auto b=parseBlock();auto s=std::make_unique<WhileStmt>();s->cond=std::move(c);s->body=std::move(b);return s;} auto e=parseExpr();accept(TokenKind::Semicolon);auto s=std::make_unique<ExprStmt>();s->expr=std::move(e);return s;}
int Parser::precedence(TokenKind k)const{switch(k){case TokenKind::OrOr:return 1;case TokenKind::AndAnd:return 2;case TokenKind::EqualEqual:case TokenKind::BangEqual:return 3;case TokenKind::Less:case TokenKind::LessEqual:case TokenKind::Greater:case TokenKind::GreaterEqual:return 4;case TokenKind::Plus:case TokenKind::Minus:return 5;case TokenKind::Star:case TokenKind::Slash:case TokenKind::Percent:return 6;default:return -1;}}
Expr::Ptr Parser::parsePrimary(){if(cur().kind==TokenKind::Integer){auto x=std::stoll(expect(TokenKind::Integer).text);return std::make_unique<IntExpr>(x);}if(cur().kind==TokenKind::String){auto s=expect(TokenKind::String).text;return std::make_unique<StringExpr>(s);}if(accept(TokenKind::KwTrue))return std::make_unique<BoolExpr>(true);if(accept(TokenKind::KwFalse))return std::make_unique<BoolExpr>(false);if(accept(TokenKind::Minus)){return std::make_unique<UnaryExpr>(TokenKind::Minus,parsePrimary());}if(accept(TokenKind::Bang)){return std::make_unique<UnaryExpr>(TokenKind::Bang,parsePrimary());}if(cur().kind==TokenKind::Identifier||cur().kind==TokenKind::KwPrint){std::string n=expect(cur().kind).text;if(accept(TokenKind::LParen)){std::vector<Expr::Ptr>a;if(cur().kind!=TokenKind::RParen){for(;;){a.push_back(parseExpr());if(!accept(TokenKind::Comma))break;}}expect(TokenKind::RParen);return std::make_unique<CallExpr>(n,std::move(a));}return std::make_unique<VarExpr>(n);}if(accept(TokenKind::LParen)){auto e=parseExpr();expect(TokenKind::RParen);return e;}throw std::runtime_error("expected expression");}
Expr::Ptr Parser::parseExpr(int minPrec){auto lhs=parsePrimary();while(true){int p=precedence(cur().kind);if(p<minPrec)break;auto op=cur().kind;++i_;auto rhs=parseExpr(p+1);lhs=std::make_unique<BinaryExpr>(op,std::move(lhs),std::move(rhs));}return lhs;}
}
