#include "codegen/llvm_ir.hpp"
#include <sstream>
#include <unordered_map>
#include <stdexcept>
namespace nexus {
class CG { public: std::ostringstream out; int reg=0,label=0; std::unordered_map<std::string,std::string> vars; std::unordered_map<std::string,Type> types;
std::string next(){return "%"+std::to_string(++reg);} std::string lab(const std::string& p){return p+std::to_string(++label);} void emit(const std::string&s){out<<s<<"\n";}
std::string esc(const std::string&s){std::ostringstream q; for(unsigned char c:s){switch(c){case '\\':q<<"\\5C";break;case '"':q<<"\\22";break;case '\n':q<<"\\0A";break;case '\r':q<<"\\0D";break;case '\t':q<<"\\09";break;default: if(c<32) {char b[5];std::snprintf(b,sizeof b,"\\%02X",c);q<<b;} else q<<c;}} return q.str();}
std::string expr(const Expr*e){if(auto*x=dynamic_cast<const IntExpr*>(e))return std::to_string(x->value);if(auto*x=dynamic_cast<const BoolExpr*>(e))return x->value?"1":"0";if(auto*x=dynamic_cast<const StringExpr*>(e)){std::string name="@.str"+std::to_string(reg+1); static std::vector<std::string>dummy; (void)name; std::string g="@.str"+std::to_string(reg+1); size_t len=x->value.size()+1; std::ostringstream pre; pre<<g; emit(g+" = private unnamed_addr constant ["+std::to_string(len)+" x i8] c\""+esc(x->value)+"\\00\", align 1");std::string p=next();emit(p+" = getelementptr inbounds ["+std::to_string(len)+" x i8], ["+std::to_string(len)+" x i8]* "+g+", i64 0, i64 0");return p;}if(auto*v=dynamic_cast<const VarExpr*>(e)){return emitLoad(v->name);}if(auto*u=dynamic_cast<const UnaryExpr*>(e)){auto a=expr(u->rhs.get()); if(u->op==TokenKind::Minus){auto r=next();emit(r+" = sub i64 0, "+a);return r;}auto r=next();emit(r+" = xor i1 "+a+", true");return r;}if(auto*b=dynamic_cast<const BinaryExpr*>(e)){auto l=expr(b->lhs.get()),r=expr(b->rhs.get()),v=next();switch(b->op){case TokenKind::Plus:emit(v+" = add i64 "+l+", "+r);return v;case TokenKind::Minus:emit(v+" = sub i64 "+l+", "+r);return v;case TokenKind::Star:emit(v+" = mul i64 "+l+", "+r);return v;case TokenKind::Slash:emit(v+" = sdiv i64 "+l+", "+r);return v;case TokenKind::Percent:emit(v+" = srem i64 "+l+", "+r);return v;case TokenKind::EqualEqual:emit(v+" = icmp eq i64 "+l+", "+r);return v;case TokenKind::BangEqual:emit(v+" = icmp ne i64 "+l+", "+r);return v;case TokenKind::Less:emit(v+" = icmp slt i64 "+l+", "+r);return v;case TokenKind::LessEqual:emit(v+" = icmp sle i64 "+l+", "+r);return v;case TokenKind::Greater:emit(v+" = icmp sgt i64 "+l+", "+r);return v;case TokenKind::GreaterEqual:emit(v+" = icmp sge i64 "+l+", "+r);return v;case TokenKind::AndAnd:emit(v+" = and i1 "+l+", "+r);return v;case TokenKind::OrOr:emit(v+" = or i1 "+l+", "+r);return v;default:break;}}if(auto*c=dynamic_cast<const CallExpr*>(e)){if(c->callee=="print"){auto a=expr(c->args[0].get()); TypeKind tk=typeOf(c->args[0].get()); if(tk==TypeKind::I64){emit("call void @nexus_print_i64(i64 "+a+")");}else if(tk==TypeKind::Bool){emit("call void @nexus_print_bool(i1 "+a+")");}else if(tk==TypeKind::String){emit("call void @nexus_print_str(ptr "+a+")");}return "0";}auto*fn=currentFns[c->callee]; std::ostringstream a; a<<"call "+llvmType(fn->ret)+" @"+fn->name+"(";for(size_t i=0;i<c->args.size();++i){if(i)a<<", ";auto av=expr(c->args[i].get());a<<llvmType(fn->params[i].type)<<" "<<av;}a<<")";if(fn->ret.kind==TypeKind::Void){emit(a.str());return "0";}std::string rr=next();emit(rr+" = "+a.str());return rr;}throw std::runtime_error("codegen expression unsupported");}
Type typeOf(const Expr*e){if(dynamic_cast<const IntExpr*>(e)||dynamic_cast<const BinaryExpr*>(e)&&false)return Type::i64();if(dynamic_cast<const BoolExpr*>(e))return Type::boolean();if(dynamic_cast<const StringExpr*>(e))return Type::string();if(auto*v=dynamic_cast<const VarExpr*>(e))return types[v->name];if(auto*u=dynamic_cast<const UnaryExpr*>(e))return typeOf(u->rhs.get());if(auto*b=dynamic_cast<const BinaryExpr*>(e)){switch(b->op){case TokenKind::EqualEqual:case TokenKind::BangEqual:case TokenKind::Less:case TokenKind::LessEqual:case TokenKind::Greater:case TokenKind::GreaterEqual:case TokenKind::AndAnd:case TokenKind::OrOr:return Type::boolean();default:return Type::i64();}}if(auto*c=dynamic_cast<const CallExpr*>(e)){if(c->callee=="print")return Type::void_();return currentFns[c->callee]->ret;}return Type::i64();}
std::string llvmType(Type t){switch(t.kind){case TypeKind::I64:return "i64";case TypeKind::Bool:return "i1";case TypeKind::String:return "ptr";case TypeKind::Void:return "void";default:return "i64";}}
std::string emitLoad(const std::string&n){auto r=next();emit(r+" = load "+llvmType(types[n])+", "+llvmType(types[n])+"* "+vars[n]);return r;}
std::unordered_map<std::string,Function*> currentFns;
void stmt(const Stmt*s,Type ret){if(auto*l=dynamic_cast<const LetStmt*>(s)){std::string ptr=next();emit(ptr+" = alloca "+llvmType(l->type));vars[l->name]=ptr;types[l->name]=l->type;auto v=expr(l->init.get());emit("store "+llvmType(l->type)+" "+v+", "+llvmType(l->type)+"* "+ptr);return;}if(auto*e=dynamic_cast<const ExprStmt*>(s)){expr(e->expr.get());return;}if(auto*r=dynamic_cast<const ReturnStmt*>(s)){if(!r->expr){emit("ret void");}else{auto v=expr(r->expr.get());emit("ret "+llvmType(ret)+" "+v);}return;}if(auto*i=dynamic_cast<const IfStmt*>(s)){auto c=expr(i->cond.get());std::string lt=lab("if.then"),lf=lab("if.else"),le=lab("if.end");emit("br i1 "+c+", label %"+lt+", label %"+lf);emit(lt+":");for(auto&x:i->thenBlock->statements)stmt(x.get(),ret);emit("br label %"+le);emit(lf+":");if(i->elseBlock)for(auto&x:i->elseBlock->statements)stmt(x.get(),ret);emit("br label %"+le);emit(le+":");return;}if(auto*w=dynamic_cast<const WhileStmt*>(s)){std::string lc=lab("while.cond"),lb=lab("while.body"),le=lab("while.end");emit("br label %"+lc);emit(lc+":");auto c=expr(w->cond.get());emit("br i1 "+c+", label %"+lb+", label %"+le);emit(lb+":");for(auto&x:w->body->statements)stmt(x.get(),ret);emit("br label %"+lc);emit(le+":");return;}}
void fn(const Function&f){vars.clear();types.clear();reg=0;emit("define "+llvmType(f.ret)+" @"+f.name+"("); // rewritten below
}
};
std::string LLVMIRGenerator::generate(const Program&p){CG g; g.currentFns.clear();for(auto&f:const_cast<Program&>(p).functions)g.currentFns[f.name]=&f;g.emit("; ModuleID = 'nexus'");g.emit("declare void @nexus_print_i64(i64)");g.emit("declare void @nexus_print_bool(i1)");g.emit("declare void @nexus_print_str(ptr)");for(auto&f:p.functions){g.vars.clear();g.types.clear();g.reg=0;std::ostringstream sig;sig<<"define "+g.llvmType(f.ret)+" @"+f.name+"(";for(size_t i=0;i<f.params.size();++i){if(i)sig<<", ";sig<<g.llvmType(f.params[i].type)<<" %arg"<<i;}sig<<") {";g.emit(sig.str());for(size_t i=0;i<f.params.size();++i){auto ptr=g.next();g.emit(ptr+" = alloca "+g.llvmType(f.params[i].type));g.emit("store "+g.llvmType(f.params[i].type)+" %arg"+std::to_string(i)+", "+g.llvmType(f.params[i].type)+"* "+ptr);g.vars[f.params[i].name]=ptr;g.types[f.params[i].name]=f.params[i].type;}g.emit("entry:");for(auto&s:f.body->statements)g.stmt(s.get(),f.ret);if(f.ret.kind==TypeKind::Void)g.emit("ret void");g.emit("}");}return g.out.str();}
}
